# Generated by Django 3.2.12 on 2022-04-11 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_remove_company_is_orphan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(help_text='Date and time of transaction')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('reversed', 'Reversed'), ('pending', 'Pending'), ('funding', 'Funding'), ('funding_user', 'Funding User')], default='pending', max_length=20)),
                ('approval_status', models.CharField(choices=[('charged', 'Charged'), ('not_charged', 'Not Charged')], default='not_charged', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
