# Generated by Django 3.2.12 on 2022-04-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('reversed', 'Reversed'), ('pending', 'Pending'), ('funding', 'Funding'), ('funding_user', 'Funding User')], default='pending', max_length=20),
        ),
    ]
