# Generated by Django 3.2.12 on 2022-04-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_orphan',
            field=models.BooleanField(default=False, help_text="It's refer to a company without name"),
        ),
    ]
